conc_analysis <- function(data.info, conc, fzm.limit, pp.num.subp){
  
  # ** Descriptive ---------------------------------
  
  ## Make frequency list, rank/frequency profile, and frequency spectrum for 
  ## concordance.
  conc.freqlist <- make_freq_list(conc)
  conc.rankprofile <- make_rank_freq_profile(conc.freqlist)
  conc.spc <- make_spc(conc)
  
  ## Save basic info (type, token, hapax) about 
  ## default fZM to dataframe (to be exported later).
  conc.info <- make_conc_basic_info_df(conc.spc)
  
  ## Add type-token ratio (types/tokens) and potential productivity
  ## (hapaxes/tokens) to info dataframe.
  conc.info["pp"] <- conc.info$hapaxes / conc.info$tokens
  conc.info["ttr"] <- conc.info$types / conc.info$tokens

  
  ## Empirical (observed) VGC.
  conc.emp.vgc <- make_empirical_growth_df(conc)
  
  # ** Interpolated VGC ---------------------------------
  
  ## Make interpolated VGC object from the frequency spectrum.
  conc.bin.vgc <- vgc.interp(conc.spc, 1:N(conc.spc))
  
  
  # ** Default fZM ---------------------------------
  
  ## Using frequency spectrum, calculate super duper basic fZM model with default settings and
  ## approximations allowed.
  conc.fzm.exact <- lnre("fzm", conc.spc, exact=T)
  conc.fzm.approx <- lnre("fzm", conc.spc, exact=F)
  
  ## Make VGC object from the basic fZM model with variances.
  conc.fzm.exact.vgc <- lnre.vgc(conc.fzm.exact, 1:fzm.limit, variances = TRUE)
  conc.fzm.approx.vgc <- lnre.vgc(conc.fzm.approx, 1:fzm.limit, variances = TRUE)
  
  ## Add these estimates of S exact and S approx to info table.
  conc.info$S.exact <- conc.fzm.exact$S
  conc.info$S.approx <- conc.fzm.approx$S
  
  ## The CI gets smaller as the curve approaches S. Hm.
  # conc.fzm.vgc <- lnre.vgc(conc.fzm, 1:fzm.limit, variances=T) 
  # plot(conc.fzm.vgc)
  
  
  # ** All fZMs with other options ---------------------------------
  
  ## Compute all fZM options, iterating through the different possible cost functions,
  ## exactness, and methods for minimising cost functions (takes a while).
  # conc.fzm.all <- gen_fzm_options(conc.spc)
  
  ## Save result to dataframe. (If parameter estimation fails, NA inserted)
  # conc.fzm.all.info <- make_fzm_info_df(conc.fzm.all)
  
  
  # ** VGCs for each fZM - TO-DO ---------------------------------
  ## TO-DO
  
  # ** PP on equally sized subsets  ---------------------------------
  ## Method 2 of comparing PP: Equalise set number of subperiods so that they all 
  ## have the same token size.
  conc.eqtok.concs <- equate_subsets_to_n_tokens(conc.info, conc, pp.num.subp)
  conc.eqtok.pp <- pp_of_equally_sized_conc_list(conc.eqtok.concs)
  
  # ** Attempts to save elegantly (failed) ---------------------------------
  
  # assign(paste0(data.info["suffix.plain"], deparse(substitute(conc.freqlist))), 
  #        conc.freqlist)
  # 
  # print(hkeitconc.freqlist)
  
  # filename <- paste0(data.info["suffix.plain"], "_conc.RData")
  # 
  # save(
  #   # parse(text=paste0(data.info["suffix.plain"], deparse(substitute(conc.freqlist)))),
  #   conc.rankprofile, conc.spc, conc.info, 
  #      file=filename)
  # 
  # return(filename)

  # ** Save one by one :/ (must be a better way) ---------------------------------
  
  saveRDS(conc.freqlist, "r-analysis/rds/conc_freqlist.rds")
  saveRDS(conc.rankprofile, "r-analysis/rds/conc_rankprof.rds")
  saveRDS(conc.spc, "r-analysis/rds/conc_spc.rds")
  saveRDS(conc.info, "r-analysis/rds/conc_info.rds")
  saveRDS(conc.emp.vgc, "r-analysis/rds/conc_emp_vgc.rds")
  saveRDS(conc.bin.vgc, "r-analysis/rds/conc_bin_vgc.rds")
  saveRDS(conc.fzm.approx, "r-analysis/rds/conc_fzm_approx.rds")
  saveRDS(conc.fzm.exact, "r-analysis/rds/conc_fzm_exact.rds")
  saveRDS(conc.fzm.approx.vgc, "r-analysis/rds/conc_fzm_approx_vgc.rds")
  saveRDS(conc.fzm.exact.vgc, "r-analysis/rds/conc_fzm_exact_vgc.rds")
  saveRDS(conc.eqtok.concs, "r-analysis/rds/conc_eqtok_concs.rds")
  saveRDS(conc.eqtok.pp, "r-analysis/rds/conc_eqtok_pp.rds")  
}

run_conc_analysis <- function(data.info, conc, fzm.extent, pp.num.subp){
  
  conc_analysis(data.info, conc, fzm.extent, pp.num.subp)
  
  ## Find all rds files generated by the conc_analysis function.
  conc.files <- list.files(pattern ="^conc.*rds$", recursive=TRUE)
  
  ## Load and save them all with the prefix of the respective suffix.
  for(idx in 1:length(conc.files)){
    assign(paste0(data.info["suffix.plain"], "_", 
                  substr(conc.files[idx], 16, nchar(conc.files[idx])-4)), 
           readRDS(conc.files[idx]),
           envir = parent.frame())
  }
}
