doc_analysis <- function(data.info, conc, tokencounts.df, norm.corpus){

  # ** Descriptive ---------------------------------
  
  ## Divide overall concordance into a list of smaller concordances by document.
  doc.titles <- as.character(tokencounts.df$title)
  doc.concs <- get_document_subsets(doc.titles, conc)
  
  ## Get frequency lists, rank/frequency profiles, and frequency spectra 
  ## for each subperiod.
  doc.freqlists <- apply_func_to_subset_list(make_freq_list, doc.concs)
  doc.rankprofiles <- apply_func_to_subset_list(make_rank_freq_profile, doc.freqlists)
  doc.spcs <- apply_func_to_subset_list(make_spc, doc.concs)
  
  doc.emp.vgc <- apply_func_to_subset_list(make_empirical_growth_df, doc.concs)
  
  ## Bind each of these into a single dataframe for export. Setting the names of list 
  ## elements first means that these names will be used as the identifiers in the new
  ## "period" column of the tall dataframe.
  names(doc.concs) <- doc.titles
  names(doc.freqlists) <- doc.titles
  names(doc.rankprofiles) <- doc.titles
  names(doc.spcs) <- doc.titles
  names(doc.emp.vgc) <- doc.titles
  
  doc.concs.tall <- bind_rows(doc.concs[!is.na(doc.concs)], .id="title")
  doc.spcs.tall <- bind_rows(doc.spcs[!is.na(doc.spcs)], .id="title")
  doc.rankprofiles.tall <- bind_rows(doc.rankprofiles[!is.na(doc.rankprofiles)], .id="title")
  doc.freqlists.tall <- bind_rows(doc.freqlists[!is.na(doc.freqlists)], .id="title")
  doc.emp.vgc.tall <- bind_rows(doc.emp.vgc[!is.na(doc.freqlists)], .id="title")
  
  doc.emp.vgc.tall.date <- "abc"
  
  ## Save info about each subperiod (types, tokens, hapaxes)
  ## in one info dataframe for all subperiods (to be exported later).
  doc.info <- make_sp_info_df(doc.spcs, doc.titles)
  
  ## Add year info into this dataframe.
  doc.info <- cbind("date" = tokencounts.df$date, doc.info)
  
  # ** Normalised counts ---------------------------------
  
  ## Add columns onto doc.info with normalised counts for types, tokens, hapaxes.
  ## Normalised pp and ttr are the same as original, because the relationship between the values
  ## is the same.
  doc.info.norm <- add_norm_to_doc_info(doc.info, tokencounts.df, norm.corpus)
  
  
  # ** ROA by document ---------------------------------
  
  ## The first row of this dataframe contains the initial lexicon.
  doc.roa <- rate_of_addition(doc.rankprofiles)
  
  ## Length of initial lexicon accessible with:
  # attr(doc.roa, 'init.lex')
  ## Also in first row of df.
  
  # ** Save data ---------------------------------
  saveRDS(doc.concs, "r-analysis/rds/doc_conc.rds")
  saveRDS(doc.concs.tall, "r-analysis/rds/doc_conc_tall.rds")
  saveRDS(doc.emp.vgc, "r-analysis/rds/doc_emp_vgc.rds")
  saveRDS(doc.emp.vgc.tall, "r-analysis/rds/doc_emp_vgc_tall.rds")
  saveRDS(doc.emp.vgc.tall.date, "r-analysis/rds/doc_emp_vgc_tall_date.rds")
  saveRDS(doc.freqlists, "r-analysis/rds/doc_freqlist.rds")
  saveRDS(doc.freqlists.tall, "r-analysis/rds/doc_freqlist_tall.rds")
  saveRDS(doc.info, "r-analysis/rds/doc_info.rds")
  saveRDS(doc.info.norm, "r-analysis/rds/doc_info_norm.rds")
  saveRDS(doc.rankprofiles, "r-analysis/rds/doc_rankprof.rds")
  saveRDS(doc.rankprofiles.tall, "r-analysis/rds/doc_rankprof_tall.rds")
  saveRDS(doc.roa, "r-analysis/rds/doc_roa.rds")
  saveRDS(doc.spcs, "r-analysis/rds/doc_spc.rds")
  saveRDS(doc.spcs.tall, "r-analysis/rds/doc_spc_tall.rds")
}

run_doc_analysis <- function(data.info, conc, tokencounts.df, norm.corpus){
  
  doc_analysis(data.info, conc, tokencounts.df, norm.corpus)
  
  ## Find all rds files generated by the conc_analysis function.
  files <- list.files(pattern ="^doc_.*rds$", recursive = TRUE)
  
  ## Load and save them all with the prefix of the respective suffix.
  for(idx in 1:length(files)){
    assign(paste0(data.info["suffix.plain"], "_", 
                  substr(files[idx], 16, nchar(files[idx])-4)), 
           readRDS(files[idx]),
           envir = parent.frame())
  }
}